#FROM vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:1.18.0-524
#FROM vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:latest
#FROM artifactory-kfs.habana-labs.com/docker-local/1.19.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.1:1.19.0-354
#FROM artifactory-kfs.habana-labs.com/docker-local/1.19.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.1:1.19.0-347
FROM  artifactory-kfs.habana-labs.com/docker-local/1.19.0/ubuntu22.04/habanalabs/pytorch-installer-2.5.1:1.19.0-561
