FROM nvcr.io/nvidia/pytorch:24.12-py3
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt update && \
    apt install graphviz
#    apt-get install -y --no-install-recommends bash nano && \
#    rm -rf /var/lib/apt/lists/*


#RUN pip install --upgrade pip
#RUN pip install pydot
#RUN pip install graphviz

RUN bash
